application: ebms160
version: 1
runtime: python
api_version: 1

handlers:
- url: /_ah/mail/.+ 
  script: handle_bounced_emails.py 
  login: admin

- url: /.*
  script: emailsender.py
  login: admin
      
inbound_services:
- mail